[book]
title = "Typhon Development Classes"
description = "A beginner programming book for the Typhon teaching language"
authors = ["Typhon project"]
language = "en"
src = "book"

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/remideboer/python-transpiler"
